---
- name: Clone Cloud-init template
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: v11
    vmid: 9000
    clone: ubuntu-jammy
    name: "{{ item.value.name }}"
    newid: "{{ item.value.vmid }}"
    storage: nvzfs
    timeout: 90
  with_items:
    - "{{ lookup('ansible.builtin.dict',quest) }}"
